spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

  datasource:
    url: jdbc:h2:file:~/db/testdb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: update